spring:
  application:
    name: Config-Prod
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://registry-service-production.up.railway.app:8761/eureka
